# Generated by Django 6.0.2 on 2026-03-15 12:49

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('shape', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('tiers', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('sponge', models.CharField(max_length=255)),
                ('filling', models.CharField(max_length=255)),
                ('icing', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True, max_length=255, null=True)),
                ('image_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image upload')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on', 'name'],
            },
        ),
    ]
