# Generated by Django 6.0.2 on 2026-03-15 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='tiers',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Tiers must be at least 1.'), django.core.validators.MaxValueValidator(3, message='Tiers cannot be more than 3.')]),
        ),
    ]
