# Generated by Django 6.0.2 on 2026-04-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverydate',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['delivery_date']},
        ),
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'ordering': ['order']},
        ),
    ]
