# Generated by Django 6.0.2 on 2026-03-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=123, max_length=80),
            preserve_default=False,
        ),
    ]
