# Generated by Django 6.0.2 on 2026-03-03 06:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_display_name_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image upload'),
        ),
    ]
