# Generated by Django 6.0.2 on 2026-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('rectangle', 'Rectangle')], default='round', max_length=20),
        ),
    ]
