# Generated by Django 6.0.2 on 2026-03-03 09:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image upload'),
        ),
    ]
