# Generated by Django 6.0.2 on 2026-03-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('rectangle', 'Rectangle'), ('cupcake', 'Cupcake')], default='round', max_length=20),
        ),
    ]
