# Generated by Django 6.0.2 on 2026-03-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_options_alter_product_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search Tags'),
        ),
    ]
